### ISSUE TITLE
Cleanup - Release Elastic IPs

### ISSUE THREAD

**Issue by maoyalu** [DevOps-Girls/DevOps-Girls-Cloud-Networking#13]
Hi,

After I applied the AWS voucher and checked the billing dashboard, I found that under the `Elastic Compute Cloud` section, `Elastic IP addresses` was billed for 121 hrs (it is cheap though).

I followed the exact same steps in the materials, but it seems that the IP addresses were not released after I deleted my VPC. I had to manually release two Elastic IP addresses. 

Can you please help me check if it is only my case?

**Comment by francalovescakes** [comment]
Thanks for the heads up! I've updated the repo just now - thank you!!
